version: '3'
services:
  flyway:
    image: ${ FLYWAY_DOCKER_IMAGE:-boxfuse/flyway:5.2.4-alpine }
    container_name: flyway
    network_mode: ${NETWORK_MODE:-host}
    environment:
      - JDBC_URL_OPTIONS
      - FLYWAY_CONNECT_RETRIES
      - FLYWAY_VALIDATE_ON_MIGRATE
      - FLYWAY_CLEAN_DISABLED
      - FLYWAY_SQL_PATH
      - FLYWAY_USER
      - FLYWAY_PASSWORD
      - FLYWAY_COMMAND
      - FLYWAY_DOCKER_IMAGE
      - FLYWAY_SCHEMAS
      - FLYWAY_DRIVER
      - JDBC_URL_OPTIONS
      - JDBC_HOST
      - JDBC_PORT
      - JDBC_URL_TYPE
      - JDBC_DATABASE
      - JDBC_DRIVER_PATH
      - JDBC_DRIVER_CACHE
      - AWS_MYSQL_DRIVER_VERSION
      - REPAIR_FIRST
      - NETWORK_MODE

    entrypoint: ['/flyway/flyway_entrypoint.sh']
    volumes:
      - '${FLYWAY_CONFIG_DIR:-config}:/flyway/config'
      - '${FLYWAY_SQL_PATH:-./src/main/resources/db/migration/}:/flyway/sql/:rw,cached'
      - '${FLYWAY_ENTRYPOINT:-.github/deployment/flyway/flyway_entrypoint.sh}:/flyway/flyway_entrypoint.sh:ro,cached'
      - '${JDBC_DRIVER_CACHE:-drivers}:${JDBC_DRIVER_PATH:-/flyway/drivers}'

volumes:
  config:
    driver: local
  drivers:
    driver: local
