name: Run Flyway Migration
description: >
  Run flyway migration

runs:
  using: 'composite'
  steps:
    - name: Publish Bash Functions To Job Steps
      uses: Broadshield/actions/actions/bash_functions@dev
    - name: Set FLYWAY_SQL_PATH
      id: path
      env:
        FLYWAY_SQL_PATH: ${{ inputs.flyway-sql-path }}
        FLYWAY_DOCKER_COMPOSE_FILE: ${{ github.action_path }}/flyway/docker-compose.yml
        FLYWAY_ENTRYPOINT: ${{ github.action_path }}/flyway/flyway_entrypoint.sh
      shell: bash
      run: |
        run_flyway_migration
