name: Load common bash functions
description: >
  Loads common bash functions used by other actions.
outputs:
  loaded:
    value: ${{ steps.bash_functions.outputs.loaded }}

runs:
  using: 'composite'
  steps:
    - uses: bitflight-devops/shell-scripts@v2.2
      name: Install shell utility scripts
    # - name: Publish Bash Functions To Job Steps
    #   id: bash_functions
    #   shell: bash
    #   run: |
    #     if [ -z "${BASH_ENV}" ]; then
    #       export BASH_ENV="${{ github.action_path }}/../../scripts/bash_functions.sh"
    #       echo "BASH_ENV=${BASH_ENV}" >>"${GITHUB_ENV}"
    #       echo "Loaded Bash Functions"
    #       echo "loaded=true" >> $GITHUB_OUTPUT
    #     else
    #       echo "loaded=false" >> $GITHUB_OUTPUT
    #     fi
