name: Install chamber
description: >
  Install Chamber
inputs:
  install-prefix:
    required: false
    type: string
    default: /usr/local/bin

runs:
  using: 'composite'
  steps:
    - uses: bitflight-devops/shell-scripts@v2.2
      name: Install shell utility scripts
    - name: Install Chamber
      id: path
      env:
        INSTALL_PREFIX: ${{ inputs.install-prefix }}
        PREFER_USERSPACE: true
      shell: bash
      run: |
        install_chamber_version
