name: Set FLYWAY_SQL_PATH
description: >
  Set absolute path to flyway schema for migration
inputs:
  flyway-sql-path:
    required: false
    type: string
outputs:
  flyway-sql-path:
    value: ${{ steps.path.outputs.flyway-sql-path }}

runs:
  using: 'composite'
  steps:
    - uses: bitflight-devops/shell-scripts@v1
      name: Install shell utility scripts
    - name: Set FLYWAY_SQL_PATH
      id: path
      env:
        FLYWAY_SQL_PATH: ${{ inputs.flyway-sql-path }}
      shell: bash
      run: |
        source "${{ github.action_path }}/get_sql_path.sh"
        get_flyway_sql_path
